---
dist: trusty
language: python
python:
- '3.6'
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: XpEqTM5DjBU+ighilRnE+XTJ3S+L9ckeL42DDJVaRbO8UWMYFhn22/y4cfbp8lfuypgvDrDCBIRWCNu01gbsKGLiSk/qASpBpk4RjuPgZCkMFpO7lubojSgEklZ8H8zNPrUtCxkd5n8y/CuYiQPAkvmh5SQXL6hgqX3fMhHDCdEpEkclSzsl9OgXnnJW2EBg5sM27SifAk+C/uAGsSttLDhxe/6e21j3/gE26MKvBbr4VPaJn6rpqyXlsWF71keS/k384+YPb9Gn5jr8cATAdiThR6Oq5cOn4OTOigcLOtX6esDaUwbJa86WcvGQ3W3MP+m72IaXdl/NBmgfK+Xgy6r6VQlaoYUcjKSC61mjTXrlQgU1AKwjcpPbq95chFEwoiGKWSS/K0I1IsDlvMVVKtgvl4pbBzT+niiL8crm3xUHPE35oziKwwoQ8iUGCFqCYzyboW5Bh3ogoqt+Eu4r1bzRZW0dcgZ4UEh+WgcH2/OtTJ0ZFL+/Ei9Qv7e8cXN/5DnXN+N1pfgl8QiBpKiao9Z6I6k9PUS+bVZEbzv5382sBKhMDlCDVvGyH2ta27pq4m8TNinvruuleR2EBpMIUALpKZcBnWBUB+tnZ+AiGUcG/CqMUlm4D7bv9/xsBUM+kFvSlfuYgx+ubSS0CxFGsIm5K2Gc9jiLTDWC7j5RQpE=
  - secure: JjU3S8TrkBBa64j+M83ARR4BeGFR0V6M/8JdOb+TsMU8G8OezNN1dT21u6hZ1E8sfTxTI2CUoDBI6+jB6Hwk8ehzS/GK/ihEinJxpgr6Gl+zBcnhovJn6WIy7bEDhIP91BP7UzpdTcCrQ6eiBbs1p5HLjAA7PJU4y6e667DS3bCCPRuVNJDbyXupWwEfVpADrrOhIJ1qsPpF4MxJhKuTPwgDSP3MB2C04uPwEnCWvif5yVOgjBNCKMwHvtaD3GyML7Fwh5DbrHT2Q9Rm7wT7F3wLUyf8kBWtPponNrpqc1NxWC45o3+cn7BSMrp2bOWVRlCdjWXgm99l9+BWcyrhZNEFl0XWgC1StHC/UKQatWY+mJ0+YpBLSz1eDjCm5y/mz3LaMtr4xRGRMDtuDccMqsKA+T49Ofe+a8KUQp1MZnbD3saISRI7OzJksWdIRXiHgSbElxoRw2Zww0egkTqZz1LdSGe5UQeg0rHK+2dbKWQWW7NHKwNcuGyUz0BUWwHS0VWSJJTZU3ewGtzqDFTLDaX4dUSs83cFTyNdRScD3u1HdTpfJUtRmnp3s78BB4eFrBkaDY1GItw9xo+Mv/rTEgQFFP/t6+cCBjrjg9InRQhsKJ8kY9eB0QZDQZE6kdSxuvxt6yDjG/tUV2lKQB2dpOgU7nrvnE604gQ9pcUCQIc=
  - secure: bWc5nODIxMtEuNG2A2jFWD3Y1DP5dCG06VCrDKEnAuC6MPHYcbpUfNgXQ6kTCpEzU/PHMDDcLzuEPsEq82AneSeHCiEZ8z15zef4JMi60Jy6CWPo9yyGx4SgTZMcDx88rwBj541xXxouSabwpD+mTY38iWvp3m4Z5oWYdF3s3HXR9uTC8AbZafjn0IN89mOLPs/wmEJNqV7VjXvWLjnMbBVoUYJg01m6Y5rl3FKHVFhbF1trCy2wjeDexgSc3y+RhfxJ68ZgVaMNbLjY8cDkXtJsGB+QzfKM+2N5afwT13gK0z5mWflVefUtNgbxLh99s1gm5GUFoTRNsYjJZKiu5oFoi29tdyre134We07mBF4RXFoZIUgUTst9LEfZ8Y+6PkqlK9UnZyBCUJNHNjF3d3JRGvXppepE9OIiUI1hhvbQxqm2KsQfLxE8zy2yXukG7ox+ZBn/6l0Mtmby19S4YTc2/QKUiCC6ebPDtsW6jziE+lKfB30kUFjv5LqUql7HoTlmnPWiB1SoeOEpbtoSnX1sdojlbXwbyTChrizrZhz7y20OWq8HjNikWtF31bmTGl795PRbkikiyWpNhIDrg+NIeKlRvl6RXpMbdXwAAC636tF2VviHAkCn0Bv2KhAZkKrsZdXW5wp/hvF0GyvVWayUhJJ4O7spKNRBhwHKGRw=
before_install:
- openssl aes-256-cbc -K $encrypted_4b262f5ae481_key -iv $encrypted_4b262f5ae481_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
install:
- pip install ansible==2.9.4 molecule apache-libcloud
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
notifications:
  slack:
    rooms:
      secure: cLpVdqfpdYAeeemHKIYsSRZIkOwvtqFIJsFvVepb4uIrxhUxwRw1ejzP0gbHEDgpRcsKoC0pD5ApIBrSOBPKK3V7R8fbWHW3fVm+lOYnNGj+JYuwqoUz6DfrNFueK8kvaHvCtPU6FFKDKXIgPGFNLcwd/SrwuRMKunP1G4O5B6tljCFgko5wfbNVDxydkZt4Pc+mmB/8gjs2/hcJg8hjfAmkrQI5LPA4zRB/jUP0oD5eBShbXsxEp7j7BHbsOyVZJQHCDw1JJjhsy8YCU4Szm8w2NzkwXdwWA3Snm+rQ6RWQIvilMyLJk10iQTSiP53YihbixDbHrbl7IEbEZdXdsh+wD+ZOpr6yVQ4YpQdAy/1/EOpvm1W5UF9//fmuc/qN/3q+yna3qI3NZVRSPDjm8oqZU+uT6G5VTPXA+U2m+WuXTjK+iluakZVz3iAquHm7uvOIT/Loaa+gNQ5PxzdLLbkCVoPSlLnT9zn9M+Pq7thvbhDGt7ylFLFEXX4/AO0AcXlfJk6YVdQ6EyRHCw5bTVU2MGMc2lXI8COsgOPd5FhOFuLEOM6yhOTDbA0NcLoZelV9uGprIrtMrZayPSNvx3yx8sOb2pltDB9XgzReE6IuHKzb0123MGLb08TnLH27h+1Y4D0tXQPxMhaxJwbY8fYWXAWpXQ4ssRHUmoXR0ZE=
git:
  quiet: true
branches:
  only:
  - master
...
